#!/bin/sh
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

fins() {
    make font.otb
	sudo cp -f font.bdf /usr/share/fonts/cursed.bdf
	sudo cp -f font.otb /usr/share/fonts/cursed.otb
    fc-cache -f -v
}

demo() {
	fins
	xterm -fa cursed -e 'less demo.txt'
}

sdemo() {
	fins
	xterm -fa cursed -e 'less shortdemo.txt'
}
