#!/bin/sh
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

install() {
	d cp -f font.bdf /usr/share/fonts/kikon/kikon.bdf
}

demo() {
	install
	xterm -fa kikon -e 'less demo.txt'
}

sdemo() {
	install
	xterm -fa kikon -e 'less shortdemo.txt'
}
